manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: testing
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: testing
      revision: zephyr/test-llcp-conn-update-fix
      import: app/west.yml
  self:
    path: config
